### ISSUE TITLE
how to set number of columns in infinite list

### ISSUE THREAD

**Issue by Shivani12345** [foundcareers/react-native-infinite-flatlist#7]
hi,i have to set items in grid form.how to set columns ?please help me, another issue : i have around 5000 items with images in array,when scroll back to list the items are invisible and turns into blank screen.Thanks you

**Comment by mcelliott** [comment]
Hi @Shivani12345,
Can you please explain what you mean by grid form and maybe include some sample code. As for the 5000 items, you will suffer for performance with this many items. I would suggest only loading what you need then page as you scroll and or filter via a search input.

**Comment by Shivani12345** [comment]
hi,
Here i have to set  items in 3 columns,but numColumns={3} is not working, here is sample code

```
<InfiniteFlatList
              data={items}
              renderItem={this._renderItem}
              loading={loading}
             numColumns={3}
            refreshing={isRefreshing}
            onRefresh={this.handleRefresh}
            removeClippedSubviews={false}
            onEndReached={this.handleLoadMore}
/>
```

**Comment by mcelliott** [comment]
OK, thanks. Currently, InfiniteFlatList doesn't expose the `numColumns` prop. I'll push a new version for this.
